apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: floodwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: floodwatch-api-gateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET
              value: "floodwatch-development-secret"
              